# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20160611_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
