# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20160827_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'permissions': (('act_analyse_parkinglot', 'Can analyse ParkingLot data'),)},
        ),
    ]
