# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0008_auto_20160928_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclein',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleout',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclein',
            name='in_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vehiclein',
            name='notice_id',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicleout',
            name='notice_id',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicleout',
            name='out_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
