# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_role1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role1',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Role1',
        ),
    ]
