# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20160427_0828'),
        ('userprofile', '0002_auto_20160415_1731'),
    ]

    operations = [
    ]
