# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_parkinglotgroup_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
