# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0005_roadsideparkingregister'),
        ('userprofile', '0006_userprofile_payment_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=100)),
                ('id_card_number', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('parking_lot', models.ManyToManyField(to='parking.ParkingLot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
