# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorprofile',
            name='parking_lots',
        ),
        migrations.RemoveField(
            model_name='operatorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parkinglotgroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='parkinglotgroup',
            name='parking_lot',
        ),
        migrations.RemoveField(
            model_name='role',
            name='owner',
        ),
        migrations.DeleteModel(
            name='OperatorProfile',
        ),
        migrations.DeleteModel(
            name='ParkingLotGroup',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
