# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidAppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.PositiveIntegerField()),
                ('vsrsion_name', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=20)),
                ('release_notes', models.CharField(max_length=500)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
