# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_apppages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androidappversion',
            old_name='vsrsion_name',
            new_name='version_name',
        ),
    ]
