# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_auto_20160912_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StartupPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
    ]
